translate_text_task:
  description: >
    Translate the following text into FALC using provided editorial and design rules.

    1. First, consult the available icons list:
      {icon_list}

    2. Use only the icon keys listed above, in the format [[ICON:icon_key]].
      Do NOT use emojis or invent new keys.
      Do NOT add icons in header, recipient, subject or footer—only in body sections for alert / warning lines.

    3. **Acronyms**
      - Do **NOT** interpret or expand any acronym from the original text.
      - Keep all acronyms exactly as they appear (e.g. LAsi, LARA, etc.)—never invent meanings.

    4. **Addressing & Procedures**
      - Include any addressing information (e.g. “à envoyer au directeur de l'EVAM, adresse”) and all procedural instructions.

    5. **Legal Citations**
      - Retain all citations of articles de loi.
      - Place them together at the very end of the final body_section paragraph.

    6. **Do NOT produce any Markdown tables** (no pipes `|`, no `---` separators).
      Instead, whenever you have logistical data, emit each item as its own paragraph, for example:
      ```
      Quand?: …
      Où?: …
      Horaires: …
      Transport: …
      Règles: …
      ```
      And for multi-line schedules, each day-line must be its own paragraph immediately following the “Horaire:” paragraph.

      This ensures the table optimizer can detect and tabulate them.

    4. Use ReferenceModelRetriever to find a matching example, then rewrite in FALC following the rules — do not copy.

    Text to translate:
    {original_text}

  expected_output: >
    Return a dictionary with keys:
      header, recipient, subject, body_sections, footer

    - header, recipient, footer may be null if not needed.
    - subject: the one-line subject.
    - body_sections: a list of paragraphs; logistical fields (Quand, Où, Horaire, Transport, Règles) must each be their own paragraph.
    - Only body_sections may contain [[ICON:…]] placeholders.

    Here's an example of a good tranlation result with the right text structure:
    """{
      "header": null,
      "recipient": "Madame",
      "subject": "Confirmation de votre participation au programme de formation et de pratique professionnelle – Session octobre 2019",
      "body_sections": [
        "Nous confirmons votre inscription au programme de formation et de pratique professionnelle en santé.",
        "Quand ?",
        "Mardi 15 octobre 2019 à 9h00.",
        "Où ?",
        "Route de Chavannes 33 à Lausanne, au 2ème étage, salle 202.",
        "Vous suivez des cours sur la santé, l'approche sociale et la vie domestique.",
        "Le premier jour, vous recevez plus d'informations sur la formation et le déroulement du programme.",
        "Nous sommes contents de vous rencontrer.",
        "Formation santé - Informations générales :",
        "La formation dure 6 mois à plein temps.",
        "Vous avez des horaires fixes :",
        "La formation théorique est de 22 heures par semaine.",
        "Lundi : de 8h30 à 12h30 et de 13h30 à 15h30.",
        "Mardi : de 8h30 à 12h30 et de 13h30 à 15h30.",
        "Jeudi : de 8h30 à 12h30 et de 13h30 à 15h30.",
        "Vendredi : de 8h30 à 12h30.",
        "Pour certains, un cours de français lié au métier a lieu le mercredi matin de 8h30 à 12h.",
        "Interventions :",
        "Les interventions pratiques sont au maximum 10 heures par semaine.",
        "Le mercredi toute la journée et le vendredi après-midi sont pour les aides à domicile.",
        "Les horaires sont irréguliers.",
        "Les participants doivent être disponibles et flexibles.",
        "Contrat :",
        "Une convention de participation pour toute la durée de la formation sera signée le premier jour.",
        "[[ICON:travail_contrat]] Votre présence aux cours est OBLIGATOIRE.",
        "[[ICON:attention_avertissement]] Ne prenez **pas** de rendez-vous médicaux, CAF ou autres pendant les heures de cours.",
        "Pause repas :",
        "Un espace pour les repas est disponible avec un micro-ondes.",
        "Vous pouvez prendre un repas au réfectoire pour un montant de CHF 3.50 ou 10 (CSIR, CRS).",
        "Un badge vous sera donné le premier jour contre une caution de CHF 10.",
        "Stage de fin de formation :",
        "Le stage dure 4 semaines dans un EMS ou institution similaire.",
        "Le stage est à plein temps avec des horaires variables.",
        "Les formatrices organisent le stage.",
        "Le stage est validé par une évaluation et un examen clinique.",
        "[[ICON:attention_avertissement]] Règles importantes :",
        "Votre présence aux cours est obligatoire.",
        "Vous ne devez **pas** prendre de rendez-vous pendant les heures de cours.",
        "Vous êtes souvent en retard ? Vous êtes absent sans excuse ? Vous allez payer une amende.",
        "",
        "| [[ICON:bases_legales]] | Art. 127 cc LARA |"
      ],
      "footer": null
    }""""

  agent: falc_translator

table_optimizer_task:
  description: >
    Review the FALC translator's `body_sections` and detect any blocks matching our three table patterns.

    ***ONLY*** these tables:

      • **Meeting Table** (“Détails de la réunion”):
        - Columns: ["Élément", "Détails"]
        - Example Rows: Quand, Où, Horaire, Transport, Règles

      • **Legal Rules Table** (“Règles légales”):
        - Columns: ["Article", "Description"]
        - Example rows for: Article, Règle

      • **Places Table** (“Liste des lieux”):
        - Columns: ["Information", "Valeur"]
        - Rows for: Contact, Adresse, Téléphone

      **Rows only** if both label and value exist in the text (do **not** create empty rows)

    When you find one of these:

      1. Gather **all consecutive paragraphs** whose field-names match one of the row keys.
      2. In `body_sections`, replace that entire group of paragraphs with a single `[[TABLE:<key>]]` placeholder.
        - Follow the FALC Guidelines for any text you place in the table.
      3. **Remove** the FALC translator text markdown formatting if any (ex: |\n| --- | --- |\n|)
      4. In `tables`, add an object:
        • key: your_key
        • title: the table title
        • columns: the two headers
        • rows: each row as `[first-column, combined second-column]`
        • hide_column_headers: true
      5. **Then scan the whole new `body_sections`** and **remove** any paragraph whose text equals any second-column value you just placed into the table.
        You MUST ensures no duplicate text remains anywhere.

    **Mandatory icons** in first-column labels for these situations:
      - Quand
      - Où
      - Quoi
      - Horaire
      - Transport
      - Règles à respecter
      - Avertissement

    Keep any `[[ICON:…]]` markers in the text you move into the table.  Do not leave any of those paragraphs behind in `body_sections`.

    Available icons:
    {icon_list}

  expected_output: >
    Return a dictionary with exactly:
      header, recipient, subject, body_sections, footer, tables

    - In `body_sections`, each detected block is replaced by `[[TABLE:<key>]]`.
    - No paragraph whose content appears in a table row may remain.
    - In `tables`, each row's first element begins with its `[[ICON:key]]` placeholder.
    - The “Règles” row's second-column entry must concatenate all rule paragraphs (with icons) into one cell.

    Here's a an example of a perfectly formated document:
    """{
      "header": null,
      "recipient": "Madame",
      "subject": "Confirmation de votre participation au programme de formation et de pratique professionnelle – Session octobre 2019",
      "body_sections": [
        "Nous confirmons votre inscription au programme de formation et de pratique professionnelle en santé.",
        "[[TABLE:meeting]]",
        "Vous suivez des cours sur la santé, l'approche sociale et la vie domestique.",
        "Le premier jour, vous recevez plus d'informations sur la formation et le déroulement du programme.",
        "Nous sommes contents de vous rencontrer.",
        "Formation santé - Informations générales :",
        "La formation dure 6 mois à plein temps.",
        "Vous avez des horaires fixes :",
        "[[TABLE:schedule]]",
        "Pour certains, un cours de français lié au métier a lieu le mercredi matin de 8h30 à 12h.",
        "Interventions :",
        "Les interventions pratiques sont au maximum 10 heures par semaine.",
        "Le mercredi toute la journée et le vendredi après-midi sont pour les aides à domicile.",
        "Les horaires sont irréguliers.",
        "Les participants doivent être disponibles et flexibles.",
        "Contrat :",
        "Une convention de participation pour toute la durée de la formation sera signée le premier jour.",
        "[[ICON:travail_contrat]] Votre présence aux cours est OBLIGATOIRE.",
        "[[ICON:attention_avertissement]] Veuillez ne pas prendre de rendez-vous médicaux, CAF ou autres pendant les heures de cours.",
        "Pause repas :",
        "Un espace pour les repas avec micro-ondes est à votre disposition.",
        "Vous pouvez prendre un repas au réfectoire pour CHF 3.50 ou CHF 10 (CSIR, CRS).",
        "Un badge vous sera remis le premier jour contre une caution de CHF 10.",
        "Stage de fin de formation :",
        "Le stage dure 4 semaines dans un EMS ou institution similaire.",
        "Le stage est à plein temps avec des horaires variables.",
        "Les formatrices organisent le stage.",
        "Le stage est validé par une évaluation et un examen clinique.",
        "[[TABLE:legal_rules]]"
      ],
      "footer": null,
      "tables": [
        {
          "key": "meeting",
          "title": "Détails de la réunion",
          "columns": ["Élément", "Détails"],
          "rows": [
            ["[[ICON:calendrier_heure_date]] Quand", "Mardi 15 octobre 2019 à 9h00."],
            ["[[ICON:localisation_ou_lieu_carte]] Où", "Route de Chavannes 33 à Lausanne, au 2ème étage, salle 202."]
          ],
          "hide_column_headers": true
        },
        {
          "key": "schedule",
          "title": "Horaire hebdomadaire",
          "columns": ["Élément", "Détails"],
          "rows": [
            ["[[ICON:heure_montre_horloge]] Horaire", "La formation théorique est de 22 heures par semaine.\nLundi : de 8h30 à 12h30 et de 13h30 à 15h30.\nMardi : de 8h30 à 12h30 et de 13h30 à 15h30.\nJeudi : de 8h30 à 12h30 et de 13h30 à 15h30.\nVendredi : de 8h30 à 12h30."]
          ],
          "hide_column_headers": true
        },
        {
          "key": "legal_rules",
          "title": "Règles légales",
          "columns": ["Article", "Description"],
          "rows": [
            ["[[ICON:respect_reglement]] Règles à respecter",
             "[[ICON:attention_avertissement]] Votre présence aux cours est obligatoire.\n[[ICON:attention_avertissement]] Vous ne devez **pas** prendre de rendez-vous pendant les heures de cours.\n[[ICON:attention_avertissement]] Vous êtes souvent en retard ? Vous êtes absent sans excuse ? Vous allez payer une amende."
            ],
            ["[[ICON:bases_legales]] Article", "Art. 127 cc LARA"]
          ],
          "hide_column_headers": true
        }
      ]
    """


  agent: table_optimizer

rewrite_original_doc_task:
  description: >
    Erase everything from paragraph index {replace_start} through {replace_end} (inclusive) in the original document,
    then insert the FALC translation (subject + body sections + tables) in that region.

    ***YOU MUST NOT*** modify the translations provided by the FALC translator.

    The following values will be passed to the writer tool:
    - header (optional)
    - recipient (optional)
    - subject
    - body_sections
    - tables (optional)
    - replace_start
    - replace_end
    - output_dir: {output_dir}

    Here's the original file path: {original_file}

  expected_output: >
    A .docx file rewritten in-place, saved as output/{session_id}/document_name_falc_TIMESTAMP.docx

  agent: falc_document_designer
